#pragma once

#define CHAR_SPEED 2
#define ZOOM_VALUE 10
#define DELTA_DIMENSION_INC 200
#define DELTA_DIMENSION_DEC 500
#define DIMENSION_SCREEN_X 640
#define DIMENSION_SCREEN_Y 480
#define COEFF_SPEED 0.2
#define COEFF_ATTACK_SPEED 0.1
#define MAP_TILESET_WIDHT 32
#define DISATANCE 38
enum
{
	LEFT,
	RIGHT,
	UP,
	DOWN
};